require 'yaml'
require_relative 'code'
require_relative 'open_classes'

module RKGEN
  class Compiler
    attr_accessor :options
    def initialize options={}
      @options=options
    end

    def compile filename
      puts "=> compiling #{filename}"
      @module_name=File.basename(filename,'.rkg').capitalize_first
      puts "=> module name is #{@module_name}"
      @spec = YAML.load_file(filename)
      @spec.inspect
      generate
      generate_visitor
    end

    def generate
      puts "=> generating classes code..."
      code=Code.new
      code << "# #{'='*60}"
      code << "# This code was generated by rkgen utility."
      code << "# DO NOT MODIFY !"
      code << "# #{'='*60}"
      code.newline
      code << "module #{@module_name}"
      code.newline
      code.indent=2
      code << generate_classes
      code.indent=0
      code << "end # #{@module_name}"
      filename="ast_#{@module_name.downcase}_rkgen.rb"
      code.save_as filename,verbose=true
    end

    def generate_classes
      code=Code.new
      code << "class AstNode"
      code.indent=2
      code << %{def accept(visitor, arg=nil)
       name = self.class.name.split(/::/).last
       visitor.send("visit\#{name}".to_sym, self ,arg) # Metaprograming !
    end

    def str
      ppr=PrettyPrinter.new
      self.accept(ppr)
    end}
      code.indent=0
      code << "end"
      @spec.each do |klass_h|
        klass_name,attributes=klass_h.first
        klass_name, inheritance=klass_name.split("<").map(&:strip).map(&:capitalize)
        inheritance||="AstNode"
        code.newline
        code << "class #{name=klass_name.capitalize_first} < #{inheritance}"
        code.indent=2

        attr_decls=attributes.map{|a| ad=a.downcase ; ":#{ad}"}.join(',')
        code << "attr_accessor #{attr_decls}"
        params=attributes.map{|a|
          ad=a.downcase
          if a.end_with?('S') #big S
            "#{ad}=[]"
          else
            "#{ad}=nil"
          end
        }.join(',')
        code << "def initialize #{params}"
        code.indent=4
        init_lhs=attributes.map{|a| ad=a.downcase ; "@#{ad}"}.join(',')
        init_rhs=attributes.map{|a| ad=a.downcase}.join(',')
        code << "#{init_lhs}=#{init_rhs}"
        code.indent=2
        code << "end"
        code.indent=0
        code << "end"
      end
      puts "=> number of classes generated : #{@spec.size}"
      code
    end

    def generate_visitor
      puts "=> generating visitor code..."
      code=Code.new
      code << "# #{'='*60}"
      code << "# This code was generated by rkgen utility."
      code << "# DO NOT MODIFY !"
      code << "# #{'='*60}"
      code.newline
      code << "module #{@module_name}"
      code.newline
      code.indent=2
      code << "class Visitor"
      code.indent=4
      code << generate_visit_entry
      code << generate_visit_methods
      code.indent=2
      code << "end # visitor"
      code.indent=0
      code << "end # #{@module_name}"
      filename="visitor_#{@module_name.downcase}_rkgen.rb"
      code.save_as filename,verbose=true
    end


    def generate_visit_entry
      code=Code.new
      code << "def visit ast"
      code.indent=2
      code << "puts \"visiting ast \#{ast}\""
      code << "ast.accept(self)"
      code.indent=0
      code << "end"
      code
    end

    def generate_visit_methods
      code=Code.new
      @spec.each{|klass_h| code << generate_visit_method(klass_h)}
      code
    end

    def generate_visit_method klass_h
      code=Code.new
      klass_name,attributes=klass_h.first
      code.newline
      code << "def visit#{klass_name.capitalize_first}(#{obj=klass_name.downcase},args=nil)"
      code.indent=2
      attributes.each do |attribute|
        if attribute.end_with?('S')
          single=attribute[0..-2]
          code << "#{obj}.#{attribute.downcase}.each{|#{single}_| #{single}_.accept(self,args)}"
        else
          code << "#{obj}.#{attribute}.accept(self,args)"
        end
      end
      code.indent=0
      code << "end"
      code
    end
  end
end
